/* attention, this file was automatically generated by swig and Perl scripts */
#include "stddef.h"
#include "omci_interface.h"
#include "me/omci_ani_g.h"
#include "me/omci_fec_pmhd.h"
#include "me/omci_gem_port_pmhd.h"
#include "me/omci_tcont.h"
#include "me/omci_sw_image.h"
#include "ifx_types.h"
#include "ifxos_common.h"
#include "ifxos_print.h"

#ifdef INCLUDE_CLI_SUPPORT

#include "lib_cli_config.h"
#include "lib_cli_core.h"

#define OMCI_CRLF IFXOS_CRLF

/** \addtogroup OMCI_CLI_COMMANDS
   @{
*/

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_version_info_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	struct omci_version version;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: version_information_get" OMCI_CRLF
		"Short Form: vig" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- char omci_version[80]" OMCI_CRLF
		"- char ifxos_version[80]" OMCI_CRLF
		"- char onu_version[80]" OMCI_CRLF
		"- char firmware_version[80]" OMCI_CRLF
		"- char omci_api_version[80]" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	fct_ret = omci_version_info_get(p_ctx, &version);
	return IFXOS_FPrintf(p_out, "errorcode=%d omci_version=\"%s\" ifxos_version=\"%s\" onu_version=\"%s\" firmware_version=\"%s\" omci_api_version=\"%s\" " OMCI_CRLF, (int)fct_ret, version.omci_version, version.ifxos_version, version.onu_version, version.firmware_version, version.omci_api_version);
}

#if !defined(OMCI_DEBUG_DISABLE)
/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_dbg_module_level_set(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	enum omci_dbg_module module;
	enum omci_dbg level;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: dbg_module_level_set" OMCI_CRLF
		"Short Form: dmls" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- enum omci_dbg_module module" OMCI_CRLF
		"   OMCI_DBG_MODULE_NO = 0" "\n"
		"   OMCI_DBG_MODULE_CORE = 1" "\n"
		"   OMCI_DBG_MODULE_API = 2" "\n"
		"   OMCI_DBG_MODULE_MIB = 3" "\n"
		"   OMCI_DBG_MODULE_ME = 4" "\n"
		"   OMCI_DBG_MODULE_MSG_DUMP = 5" "\n"
		"   OMCI_DBG_MODULE_PM = 6" "\n"
		"   OMCI_DBG_MODULE_MIB_RESET = 7" "\n"
		"   OMCI_DBG_MODULE_IFXOS = 8" "\n"
		"   OMCI_DBG_MODULE_VOIP = 9" "\n"
		"   OMCI_DBG_MODULE_MCC = 10" "\n"
		"- enum omci_dbg level" OMCI_CRLF
		"   OMCI_DBG_MSG = 0" "\n"
		"   OMCI_DBG_PRN = 1" "\n"
		"   OMCI_DBG_WRN = 2" "\n"
		"   OMCI_DBG_ERR = 3" "\n"
		"   OMCI_DBG_OFF = 4" "\n"
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%u %u", &module, &level);
	if (ret != 2) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_dbg_module_level_set(module, level);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_dbg_module_level_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	enum omci_dbg_module module;
	enum omci_dbg level;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: dbg_module_level_get" OMCI_CRLF
		"Short Form: dmlg" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- enum omci_dbg_module module" OMCI_CRLF
		"   OMCI_DBG_MODULE_NO = 0" "\n"
		"   OMCI_DBG_MODULE_CORE = 1" "\n"
		"   OMCI_DBG_MODULE_API = 2" "\n"
		"   OMCI_DBG_MODULE_MIB = 3" "\n"
		"   OMCI_DBG_MODULE_ME = 4" "\n"
		"   OMCI_DBG_MODULE_MSG_DUMP = 5" "\n"
		"   OMCI_DBG_MODULE_PM = 6" "\n"
		"   OMCI_DBG_MODULE_MIB_RESET = 7" "\n"
		"   OMCI_DBG_MODULE_IFXOS = 8" "\n"
		"   OMCI_DBG_MODULE_VOIP = 9" "\n"
		"   OMCI_DBG_MODULE_MCC = 10" "\n"
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- enum omci_dbg level" OMCI_CRLF
		"   OMCI_DBG_MSG = 0" "\n"
		"   OMCI_DBG_PRN = 1" "\n"
		"   OMCI_DBG_WRN = 2" "\n"
		"   OMCI_DBG_ERR = 3" "\n"
		"   OMCI_DBG_OFF = 4" "\n"
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%u", &module);
	if (ret != 1) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_dbg_module_level_get(module, &level);
	return IFXOS_FPrintf(p_out, "errorcode=%d level=%u " OMCI_CRLF, (int)fct_ret, level);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_dbg_level_set(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	enum omci_dbg level;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: dbg_level_set" OMCI_CRLF
		"Short Form: dls" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- enum omci_dbg level" OMCI_CRLF
		"   OMCI_DBG_MSG = 0" "\n"
		"   OMCI_DBG_PRN = 1" "\n"
		"   OMCI_DBG_WRN = 2" "\n"
		"   OMCI_DBG_ERR = 3" "\n"
		"   OMCI_DBG_OFF = 4" "\n"
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%u", &level);
	if (ret != 1) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_dbg_level_set(level);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

#endif /* !defined(OMCI_DEBUG_DISABLE) */
/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_alarm_set(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	uint16_t instance_id;
	unsigned int alarm;
	bool active;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_alarm_set" OMCI_CRLF
		"Short Form: meas" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- uint16_t instance_id" OMCI_CRLF
		"- unsigned int alarm" OMCI_CRLF
		"- bool active \n   false = 0\n   true = 1" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %hu %u %bu", &class_id, &instance_id, &alarm, &active);
	if (ret != 4) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_alarm_set(p_ctx, class_id, instance_id, alarm, active);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_alarm_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	uint16_t instance_id;
	unsigned int alarm;
	bool active;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_alarm_get" OMCI_CRLF
		"Short Form: meag" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- uint16_t instance_id" OMCI_CRLF
		"- unsigned int alarm" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- bool active \n   false = 0\n   true = 1" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %hu %u", &class_id, &instance_id, &alarm);
	if (ret != 3) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_alarm_get(p_ctx, class_id, instance_id, alarm, &active);
	return IFXOS_FPrintf(p_out, "errorcode=%d active=%u " OMCI_CRLF, (int)fct_ret, active);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_processing_enable(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	bool enable;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: processing_enable" OMCI_CRLF
		"Short Form: pe" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- bool enable \n   false = 0\n   true = 1" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%bu", &enable);
	if (ret != 1) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_processing_enable(p_ctx, enable);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_delete(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	uint16_t instance_id;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_delete" OMCI_CRLF
		"Short Form: med" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- uint16_t instance_id" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %hu", &class_id, &instance_id);
	if (ret != 2) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_delete(p_ctx, class_id, instance_id);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_prop_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	enum omci_me_prop me_prop;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: class_prop_get" OMCI_CRLF
		"Short Form: cpg" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- enum omci_me_prop me_prop" OMCI_CRLF
		"   OMCI_ME_PROP_NONE = 0" "\n"
		"   OMCI_ME_PROP_NO_UPLOAD = 1 << 0" "\n"
		"   OMCI_ME_PROP_HAS_ALARMS = 1 << 1" "\n"
		"   OMCI_ME_PROP_HAS_ARC = 1 << 2" "\n"
		"   OMCI_ME_PROP_PM = 1 << 3" "\n"
		"   OMCI_ME_PROP_PM_INTERNAL = 1 << 4" "\n"
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu", &class_id);
	if (ret != 1) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_prop_get(p_ctx, class_id, &me_prop);
	return IFXOS_FPrintf(p_out, "errorcode=%d me_prop=%u " OMCI_CRLF, (int)fct_ret, me_prop);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_attr_size_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	unsigned int attr;
	size_t attr_size;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_attr_size_get" OMCI_CRLF
		"Short Form: measg" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- unsigned int attr" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- size_t attr_size" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %u", &class_id, &attr);
	if (ret != 2) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_attr_size_get(p_ctx, class_id, attr, &attr_size);
	return IFXOS_FPrintf(p_out, "errorcode=%d attr_size=%lu " OMCI_CRLF, (int)fct_ret, attr_size);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_attr_prop_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	unsigned int attr;
	enum omci_attr_prop attr_prop;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_attr_prop_get" OMCI_CRLF
		"Short Form: meapg" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- unsigned int attr" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- enum omci_attr_prop attr_prop" OMCI_CRLF
		"   OMCI_ATTR_PROP_NONE = 0x0" "\n"
		"   OMCI_ATTR_PROP_RD = 0x1" "\n"
		"   OMCI_ATTR_PROP_WR = 0x2" "\n"
		"   OMCI_ATTR_PROP_SBC = 0x4" "\n"
		"   OMCI_ATTR_PROP_AVC = 0x8" "\n"
		"   OMCI_ATTR_PROP_NOT_SUPPORTED = 0x10" "\n"
		"   OMCI_ATTR_PROP_NO_UPLOAD = 0x20" "\n"
		"   OMCI_ATTR_PROP_TABLE = 0x40" "\n"
		"   OMCI_ATTR_PROP_NO_SWAP = 0x80" "\n"
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %u", &class_id, &attr);
	if (ret != 2) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_attr_prop_get(p_ctx, class_id, attr, &attr_prop);
	return IFXOS_FPrintf(p_out, "errorcode=%d attr_prop=%u " OMCI_CRLF, (int)fct_ret, attr_prop);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_attr_type_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	unsigned int attr;
	enum omci_attr_type attr_type;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_attr_type_get" OMCI_CRLF
		"Short Form: meatg" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- unsigned int attr" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- enum omci_attr_type attr_type" OMCI_CRLF
		"   OMCI_ATTR_TYPE_UNKNOWN = 0" "\n"
		"   OMCI_ATTR_TYPE_PTR = 1" "\n"
		"   OMCI_ATTR_TYPE_BF = 2" "\n"
		"   OMCI_ATTR_TYPE_INT = 3" "\n"
		"   OMCI_ATTR_TYPE_UINT = 4" "\n"
		"   OMCI_ATTR_TYPE_STR = 5" "\n"
		"   OMCI_ATTR_TYPE_ENUM = 6" "\n"
		"   OMCI_ATTR_TYPE_TBL = 7" "\n"
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %u", &class_id, &attr);
	if (ret != 2) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_attr_type_get(p_ctx, class_id, attr, &attr_type);
	return IFXOS_FPrintf(p_out, "errorcode=%d attr_type=%u " OMCI_CRLF, (int)fct_ret, attr_type);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_attr_offset_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	unsigned int attr;
	size_t attr_offset;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_attr_offset_get" OMCI_CRLF
		"Short Form: meaog" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- unsigned int attr" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- size_t attr_offset" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %u", &class_id, &attr);
	if (ret != 2) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_attr_offset_get(p_ctx, class_id, attr, &attr_offset);
	return IFXOS_FPrintf(p_out, "errorcode=%d attr_offset=%lu " OMCI_CRLF, (int)fct_ret, attr_offset);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_count_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	size_t count;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_count_get" OMCI_CRLF
		"Short Form: mecg" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- size_t count" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	fct_ret = omci_me_count_get(p_ctx, &count);
	return IFXOS_FPrintf(p_out, "errorcode=%d count=%lu " OMCI_CRLF, (int)fct_ret, count);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_attr_change(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	uint16_t instance_id;
	uint16_t attr;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: attr_change" OMCI_CRLF
		"Short Form: ac" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- uint16_t instance_id" OMCI_CRLF
		"- uint16_t attr" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %hu %hu", &class_id, &instance_id, &attr);
	if (ret != 3) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_attr_change(p_ctx, class_id, instance_id, attr);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_interval_end(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint8_t interval_end_time;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: interval_end" OMCI_CRLF
		"Short Form: ie" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint8_t interval_end_time" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%bu", &interval_end_time);
	if (ret != 1) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_interval_end(p_ctx, interval_end_time);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}
/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_olt_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	enum omci_olt pOlt;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: olt_get" OMCI_CRLF
		"Short Form: og" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- enum omci_olt pOlt" OMCI_CRLF
		"   OMCI_OLT_UNKNOWN = 0" "\n"
		"   OMCI_OLT_NSN = 1" "\n"
		"   OMCI_OLT_MOTO = 2" "\n"
		"   OMCI_OLT_OPENCON = 3" "\n"
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	fct_ret = omci_olt_get(p_ctx, &pOlt);
	return IFXOS_FPrintf(p_out, "errorcode=%d pOlt=%u " OMCI_CRLF, (int)fct_ret, pOlt);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_mib_reset(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: mib_reset" OMCI_CRLF
		"Short Form: mr" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	fct_ret = omci_mib_reset(p_ctx);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_me_is_supported(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: managed_entity_is_supported" OMCI_CRLF
		"Short Form: meis" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu", &class_id);
	if (ret != 1) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_me_is_supported(p_ctx, class_id);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_failsafe_enable(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	bool enable;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: failsafe_enable" OMCI_CRLF
		"Short Form: fe" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- bool enable \n   false = 0\n   true = 1" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%bu", &enable);
	if (ret != 1) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_failsafe_enable(p_ctx, enable);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_action_timeout_set(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint32_t action_timeout;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: action_timeout_set" OMCI_CRLF
		"Short Form: ats" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint32_t action_timeout" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%u", &action_timeout);
	if (ret != 1) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_action_timeout_set(p_ctx, action_timeout);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_action_timeout_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint32_t action_timeout;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: action_timeout_get" OMCI_CRLF
		"Short Form: atg" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- uint32_t action_timeout" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	fct_ret = omci_action_timeout_get(p_ctx, &action_timeout);
	return IFXOS_FPrintf(p_out, "errorcode=%d action_timeout=%u " OMCI_CRLF, (int)fct_ret, action_timeout);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_msg_num_get(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	unsigned int num;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: msg_num_get" OMCI_CRLF
		"Short Form: mng" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		"- unsigned int num" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	fct_ret = omci_msg_num_get(p_ctx, &num);
	return IFXOS_FPrintf(p_out, "errorcode=%d num=%u " OMCI_CRLF, (int)fct_ret, num);
}

/** Handle command

   \param[in] p_ctx     OMCI context pointer
   \param[in] p_cmd     Input commands
   \param[in] p_out     Output FD
*/
static int cli_omci_attr_avc_send(
	void *p_ctx,
	const char *p_cmd,
	IFXOS_File_t *p_out)
{
	int ret = 0;
	enum omci_error fct_ret = (enum omci_error) 0;
	uint16_t class_id;
	uint16_t instance_id;
	unsigned int attr;

#ifndef OMCI_DEBUG_DISABLE
	static const char usage[] =
		"Long Form: attr_avc_send" OMCI_CRLF
		"Short Form: aas" OMCI_CRLF
		OMCI_CRLF
		"Input Parameter" OMCI_CRLF
		"- uint16_t class_id" OMCI_CRLF
		"- uint16_t instance_id" OMCI_CRLF
		"- unsigned int attr" OMCI_CRLF
		OMCI_CRLF
		"Output Parameter" OMCI_CRLF
		"- enum omci_error error" OMCI_CRLF
		OMCI_CRLF;
#else
#undef usage
#define usage ""
#endif

	if ((ret = cli_check_help__file(p_cmd, usage, p_out)) != 0) {
		return ret;
	}
	ret = cli_sscanf(p_cmd, "%hu %hu %u", &class_id, &instance_id, &attr);
	if (ret != 3) {
		return cli_check_help__file("-h", usage, p_out);
	}
	fct_ret = omci_attr_avc_send(p_ctx, class_id, instance_id, attr);
	return IFXOS_FPrintf(p_out, "errorcode=%d " OMCI_CRLF, (int)fct_ret);
}

/** Register autogenerated commands */
int cli_autogen_commands_register(struct cli_core_context_s *p_core_ctx)
{
unsigned int group_mask = 0;
(void)cli_core_key_add__file(p_core_ctx, group_mask, "vig", "version_information_get", cli_omci_version_info_get);
#if !defined(OMCI_DEBUG_DISABLE)
(void)cli_core_key_add__file(p_core_ctx, group_mask, "dmls", "dbg_module_level_set", cli_omci_dbg_module_level_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "dmlg", "dbg_module_level_get", cli_omci_dbg_module_level_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "dls", "dbg_level_set", cli_omci_dbg_level_set);
#endif /* !defined(OMCI_DEBUG_DISABLE) */
(void)cli_core_key_add__file(p_core_ctx, group_mask, "meas", "managed_entity_alarm_set", cli_omci_me_alarm_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "meag", "managed_entity_alarm_get", cli_omci_me_alarm_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "pe", "processing_enable", cli_omci_processing_enable);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "med", "managed_entity_delete", cli_omci_me_delete);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "cpg", "class_prop_get", cli_omci_me_prop_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "measg", "managed_entity_attr_size_get", cli_omci_me_attr_size_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "meapg", "managed_entity_attr_prop_get", cli_omci_me_attr_prop_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "meatg", "managed_entity_attr_type_get", cli_omci_me_attr_type_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "meaog", "managed_entity_attr_offset_get", cli_omci_me_attr_offset_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "mecg", "managed_entity_count_get", cli_omci_me_count_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "ac", "attr_change", cli_omci_attr_change);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "ie", "interval_end", cli_omci_interval_end);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "og", "olt_get", cli_omci_olt_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "mr", "mib_reset", cli_omci_mib_reset);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "meis", "managed_entity_is_supported", cli_omci_me_is_supported);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "fe", "failsafe_enable", cli_omci_failsafe_enable);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "ats", "action_timeout_set", cli_omci_action_timeout_set);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "atg", "action_timeout_get", cli_omci_action_timeout_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "mng", "msg_num_get", cli_omci_msg_num_get);
(void)cli_core_key_add__file(p_core_ctx, group_mask, "aas", "attr_avc_send", cli_omci_attr_avc_send);
return 0;
}

/*! @} */

#endif
