/******************************************************************************

                              Copyright (c) 2011
                            Lantiq Deutschland GmbH
                     Am Campeon 3; 85579 Neubiberg, Germany

  For licensing information, see the file 'LICENSE' in the root folder of
  this software module.

******************************************************************************/
#ifndef _omci_ethernet_pmhd_h
#define _omci_ethernet_pmhd_h

#ifndef SWIG
#include "omci_interface.h"
#endif

__BEGIN_DECLS

/** \addtogroup OMCI_ME
   @{
*/

/** \defgroup OMCI_ME_ETHERNET_PMHD Ethernet Performance Monitoring History Data Managed Entity

    These Managed Entities collect performance monitoring data for an Ethernet
    interface.

    Instances of these Managed Entities are created and deleted by the OLT.
    An instance of this Managed Entity is associated with an instance of the
    physical path termination point Ethernet UNI.

    @{
*/

/** This structure holds the attributes of the Ethernet Performance Monitoring
    History Data Managed Entity.
*/
struct omci_me_ethernet_pmhd {
	/** Interval End Time

	    This attribute identifies the most recently finished 15-minute
	    interval. The sequence of 15-minute intervals is initiated by the
	    synchronize time action, issued by the OLT. The counter is
	    incremented every 15 minutes autonomously by the ONU and rolls over
	    from 255 to 0.

	    This attribute is read-only by the OLT.
	*/
	uint8_t interval_end_time;

	/** Threshold Data 1/2 ID

	    This attribute points to an instance of the threshold data 1 Managed
	    Entity that contains PM threshold values.
	    Since no threshold value attribute number exceeds 7, a threshold
	    data 2 Managed Entity is optional.

	    This attribute is readable and writable by the OLT.
	*/
	uint16_t thr_data_id;

	/** FCS Error Count

	    This attribute counts frames received on a particular interface that
	    were an integral number of octets in length but failed the frame
	    check sequence (FCS) check. The count is incremented when the MAC
	    service returns the frameCheckError status to the link layer control
	    (LLC) or other MAC user.
	    Received frames for which multiple error conditions are obtained are
	    counted according to the error status presented to the LLC.

	    This attribute is read-only for the OLT.
	*/
	uint32_t fcs_error_count;

	/** Excessive Collision Count

	    This attribute counts frames whose transmission failed due to
	    excessive collisions.

	    \remarks This counter is not used in full duplex operation mode.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t excesive_collision_count;

	/** Late Collision Count

	    This attribute counts the number of times that a collision was
	    detected later than 512 bit times into the transmission of a packet.

	    \remarks This counter is not used in full duplex operation mode.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t late_collision_count;

	/** Frames Too Long Count

	    This attribute counts received frames that exceeded the maximum
	    permitted frame size. The count is incremented when the MAC service
	    returns the frameTooLong status to the LLC.
	*/
	uint32_t frame_too_long_count;

	/** Receive Buffer Overflow Count

	    This attribute counts the number of times that the receive buffer
	    reached its maximum limit and could not accept the incoming frame.
	*/
	uint32_t rx_buffer_overflow_count;

	/** Transmit Buffer Overflow Count

	    This attribute counts the number of times that the transmit buffer
	    could not accept a frame to be transmitted and had to discard the
	    frame.
	*/
	uint32_t tx_buffer_overflow_count;

	/** Single Collision Count

	    This attribute counts successfully transmitted frames whose
	    transmission was delayed by exactly one collision.

	    \remarks This counter is not used in full duplex operation mode.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t single_collision_count;

	/** Multiple Collision Count

	    This attribute counts successfully transmitted frames
	    whose transmission was delayed by more than one collision.

	    \remarks This counter is not used in full duplex operation mode.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t multiple_collision_count;

	/** Signal Quality Error Test Count

	    This attribute counts the number of times that the SQE test error
	    message was generated by the PLS sublayer.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t signal_quality_error_count;

	/** Deferred Transmission Count

	    This attribute counts frames whose first transmission
	    attempt was delayed because the medium was busy.
	    The count does not include frames involved in collisions.

	    \remarks This counter is not used in full duplex operation mode.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t deferred_transmission_count;

	/** Internal MAC Transmit Error Count

	    This attribute counts frames whose transmission
	    failed due to an internal MAC sublayer transmit error.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t mac_tx_error_count;

	/** Carrier Sense Error Count

	    This attribute counts the number of times that carrier sense
	    was lost or never asserted when attempting to transmit a frame.

	    \remarks This counter is not used in full duplex operation mode.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t carrier_sense_error_count;

	/** Alignment Error Count

	    This attribute counts received frames that were not an integral
	    number of octets in length and did not pass the FCS check.
	*/
	uint32_t aligment_error_count;

	/** Internal MAC Receive Error Count

	    This attribute counts frames whose reception failed
	    due to an internal MAC sublayer receive error.

	    \remarks This counter is not supported by hardware.
	    It always returns a value of zero.
	*/
	uint32_t internal_mac_rx_error_count;

} __PACKED__;

/** This enumerator holds the attribute numbers of the Ethernet Performance
   Monitoring History Data Managed Entity.
*/
enum {
	omci_me_ethernet_pmhd_interval_end_time = 1,
	omci_me_ethernet_pmhd_thr_data_id = 2,
	omci_me_ethernet_pmhd_fcs_error_count = 3,
	omci_me_ethernet_pmhd_excessive_collision_count = 4,
	omci_me_ethernet_pmhd_late_collision_count = 5,
	omci_me_ethernet_pmhd_frame_too_long_count = 6,
	omci_me_ethernet_pmhd_rx_buffer_overflow_count = 7,
	omci_me_ethernet_pmhd_tx_buffer_overflow_count = 8,
	omci_me_ethernet_pmhd_single_collision_count = 9,
	omci_me_ethernet_pmhd_multiple_collision_count = 10,
	omci_me_ethernet_pmhd_signal_quality_error_count = 11,
	omci_me_ethernet_pmhd_deferred_transmission_count = 12,
	omci_me_ethernet_pmhd_mac_tx_error_count = 13,
	omci_me_ethernet_pmhd_carrier_sense_error_count = 14,
	omci_me_ethernet_pmhd_alignment_error_count = 15,
	omci_me_ethernet_pmhd_internal_mac_rx_error_count = 16
};

/** @} */

/** @} */

__END_DECLS

#endif
